@include("site.components.header", ['title' => 'Home - HARFUN'])
@include("site.components.home.banner")
@include("site.components.home.categories")
@include("site.components.home.counters")
@include("site.components.home.new_jobs")
@include("site.components.home.reviews")
@include("site.components.home.find_talent")
@include("site.components.home.faqs")
@include("site.components.home.portal_intro")
@include("site.components.footer")